### ISSUE TITLE
AllCS Dataset Download

### ISSUE THREAD

**Issue by IamAdiSri** [ishan00/translation-for-code-switching-acl#1]
Hi, I downloaded the AllCS Dataset as given [here](https://www.cse.iitb.ac.in/~pjyothi/CS/), but noticed that it only contains around 14.6k samples between the train, valid and test splits. In your paper you've mentioned there being 21.4k samples in total which is significantly greater. Is there anywhere I can download the full dataset?

**Comment by ishan00** [comment]
Sorry for the late reply. 

There are 14.6K monolingual lines but there are one or more-than-one CS lines per monolingual line. So by using all the lines from `gold` and `mturk`, you will get 21.4K CS lines. In the current repository you can directly use data/All-CS/en.train file for CS data. It has 21.4K lines
